import asyncio

from HackfreaksUserbot import CMD_HELP
from HackfreaksUserbot.utils import Hackfreaks_on_cmd


@Hackfreaks.on(Hackfreaks_on_cmd(pattern="alone ?(.*)"))
async def _(event):
    if not event.text[0].isalpha() and event.text[0] not in ("/", "#", "@", "!"):
        await event.edit("T")
        await asyncio.sleep(0.7)
        await event.edit("Th")
        await asyncio.sleep(0.7)
        await event.edit("The")
        await asyncio.sleep(0.7)
        await event.edit("The D")
        await asyncio.sleep(0.7)
        await event.edit("The Da")
        await asyncio.sleep(0.7)
        await event.edit("The Day")
        await asyncio.sleep(0.7)
        await event.edit("The Day I")
        await asyncio.sleep(0.7)
        await event.edit("The Day I L")
        await asyncio.sleep(0.7)
        await event.edit("The Day I Le")
        await asyncio.sleep(0.7)
        await event.edit("The Day I Lea")
        await asyncio.sleep(0.7)
        await event.edit("The Day I Lear")
        await asyncio.sleep(0.7)
        await event.edit("The Day I Learn")
        await asyncio.sleep(0.7)
        await event.edit("The Day I Learnt")
        await asyncio.sleep(0.7)
        await event.edit("The Day I Learnt T")
        await asyncio.sleep(0.7)
        await event.edit("The Day I Learnt To")
        await asyncio.sleep(0.7)
        await event.edit("The Day I Learnt To L")
        await asyncio.sleep(0.7)
        await event.edit("The Day I Learnt To Li")
        await asyncio.sleep(0.7)
        await event.edit("The Day I Learnt To Liv")
        await asyncio.sleep(0.7)
        await event.edit("The Day I Learnt To Live")
        await asyncio.sleep(0.7)
        await event.edit("The Day I Learnt To Live A")
        await asyncio.sleep(0.7)
        await event.edit("The Day I Learnt To Live Al")
        await asyncio.sleep(0.7)
        await event.edit("The Day I Learnt To Live Alo")
        await asyncio.sleep(0.7)
        await event.edit("The Day I Learnt To Live Alon")
        await asyncio.sleep(0.7)
        await event.edit("Tge Day I Learnt To Live Alone")
        await asyncio.sleep(0.7)
        await event.edit("The Day I Learnt To Live Alone \nE")
        await asyncio.sleep(0.7)
        await event.edit("The Day I Learnt To Live Alone \nEv")
        await asyncio.sleep(0.7)
        await event.edit("The Day I Learnt To Live Alone \nEve")
        await asyncio.sleep(0.7)
        await event.edit("The Day I Learnt To Live Alone \nEver")
        await asyncio.sleep(0.7)
        await event.edit("The Day I Learnt To Live Alone \nEvery")
        await asyncio.sleep(0.7)
        await event.edit("The Day I Learnt To Live Alone \nEveryt")
        await asyncio.sleep(0.7)
        await event.edit("The Day I Learnt To Live Alone \nEveryth")
        await asyncio.sleep(0.7)
        await event.edit("The Day I Learnt To Live Alone \nEverythi")
        await asyncio.sleep(0.7)
        await event.edit("The Day I Learnt To Live Alone \nEverythin")
        await asyncio.sleep(0.7)
        await event.edit("The Day I Learnt To Live Alone \nEverything")
        await asyncio.sleep(0.7)
        await event.edit("The Day I Learnt To Live Alone \nEverything B")
        await asyncio.sleep(0.7)
        await event.edit("The Day I Learnt To Live Alone \nEverything Be")
        await asyncio.sleep(0.7)
        await event.edit("The Day I Learnt To Live Alone \nEverything Bec")
        await asyncio.sleep(0.7)
        await event.edit("The Day I Learnt To Live Alone \nEverything Beca")
        await asyncio.sleep(0.7)
        await event.edit("The Day I Learnt To Live Alone \nEverything Becam")
        await asyncio.sleep(0.7)
        await event.edit("The Day I Learnt To Live Alone \nEverything Became")
        await asyncio.sleep(0.7)
        await event.edit("The Day I Learnt To Live Alone \nEverything Became B")
        await asyncio.sleep(0.7)
        await event.edit("The Say I Learnt To Live Alone \nEverything Became Be")
        await asyncio.sleep(0.7)
        await event.edit("The Day I Learnt To Live Alone \nEverything Became Bea")
        await asyncio.sleep(0.7)
        await event.edit("The Day I Learnt To Live Alone \nEverything Became Beau")
        await asyncio.sleep(0.7)
        await event.edit("The Day I Learnt To Live Alone \nEverything Became Beaut")
        await asyncio.sleep(0.7)
        await event.edit("The Day I Learnt To Live Alone \nEverything Became Beauti")
        await asyncio.sleep(0.7)
        await event.edit("The Day I Learnt To Live Alone \nEverything Became Beautif")
        await asyncio.sleep(0.7)
        await event.edit("The Day I Learnt To Live Alone \nEverything Became Beautifu")
        await asyncio.sleep(0.7)
        await event.edit("The Day I Learnt To Live Alone \nEverything Became Beautiful")
        await asyncio.sleep(0.7)
        await event.edit(
            "**The Day I Learnt To Live Alone \nEverything Became Beautiful**🙂"
        )


CMD_HELP.update(
    {
        "alone": "Alone\
\n\nSyntax : .alone \
\nUsage : Lyrics Of Alone Song"
    }
)
