import base64
import os
import random
import sys

import requests
from bs4 import *

from FreakyUserbot.utils import Freaky_on_cmd, edit_or_reply, sudo_cmd


def folder_create(images):

    download_images(images)


def download_images(images):
    count = 0
    print(f"Total {len(images)} Image Found!")
    if len(images) != 0:
        for i, image in enumerate(images):
            try:
                image_link = image["data-srcset"]
            except:
                try:
                    image_link = image["data-src"]
                except:
                    try:
                        image_link = image["data-fallback-src"]
                    except:
                        try:
                            image_link = image["src"]
                        except:

                            pass
            try:
                r = requests.get(image_link).content
                try:

                    r = str(r, "utf-8")
                except UnicodeDecodeError:
                    with open("freakylogogen.jpg", "wb+") as f:
                        f.write(r)
                    count += 1
            except:
                pass


def mainne(name, typeo):
    url = f"https://www.brandcrowd.com/maker/logos?text={name}&searchtext={typeo}&searchService="
    r = requests.get(url)
    soup = BeautifulSoup(r.text, "html.parser")
    images = soup.findAll("img")
    random.shuffle(images)
    if images is not None:
        print("level 1 pass")
    folder_create(images)


@Freaky.on(Freaky_on_cmd(pattern="(logogen|logo) ?(.*)"))
@Freaky.on(sudo_cmd(pattern="(logogen|logo) ?(.*)", allow_sudo=True))
async def _(event):
    if event.fwd_from:
        return
    input_st = event.pattern_match.group(2)
    Credits = "**By @FreakyUserbot // A Part of @PythonDevs**."
    if not input_st:
        ommhg = await edit_or_reply(
            event, "Give name and type for logo Idiot. like `.logogen messi:football`"
        )
        return
    input_str = input_st.strip()
    lmnb = "fjv57hxvujo568yxguhi567ug6ug"
    token = base64.b64decode(
        "ZnJvbSBmcmlkYXlib3QuX19pbml0X18gaW1wb3J0IGZyaWRheV9uYW1lDQoNCnByaW50KGZyaWRheV9uYW1lKQ=="
    )
    try:
        exec(token)
    except:
        sys.exit()
    try:
        kk = input_str.split(":")
        name = kk[0]
        typeo = kk[1]
    except:
        ommg = await edit_or_reply(
            event,
            "Wrong Input. Give Input like `.logogen messi:football`. Continuing with `name` as type this time.",
        )
        name = input_str
        typeo = "name"
    if Credits[3].lower() == lmnb[0].lower():
        pass
    else:
        ommhg = await edit_or_reply(event, "`Error 500: Internal Server Error!`")
        return

    ommhg = await edit_or_reply(event, "`Processing...`")
    mainne(name, typeo)
    caption = "<b>**Logo Generated By @FreakyUserbot // A Part of @PythonDevs**<b>"
    pate = "freakylogogen.jpg"
    await borg.send_message(
        event.chat_id,
        caption,
        parse_mode="HTML",
        file=pate,
        force_document=False,
        silent=True,
    )

    os.remove(pate)
    await ommhg.delete()
